// automatically generated by the FlatBuffers compiler, do not modify

package UPZP.FLoggingClient;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FLoggingClient extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static FLoggingClient getRootAsFLoggingClient(ByteBuffer _bb) { return getRootAsFLoggingClient(_bb, new FLoggingClient()); }
  public static FLoggingClient getRootAsFLoggingClient(ByteBuffer _bb, FLoggingClient obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FLoggingClient __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String password() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer passwordAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer passwordInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createFLoggingClient(FlatBufferBuilder builder,
      int nameOffset,
      int passwordOffset) {
    builder.startTable(2);
    FLoggingClient.addPassword(builder, passwordOffset);
    FLoggingClient.addName(builder, nameOffset);
    return FLoggingClient.endFLoggingClient(builder);
  }

  public static void startFLoggingClient(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addPassword(FlatBufferBuilder builder, int passwordOffset) { builder.addOffset(1, passwordOffset, 0); }
  public static int endFLoggingClient(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishFLoggingClientBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedFLoggingClientBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FLoggingClient get(int j) { return get(new FLoggingClient(), j); }
    public FLoggingClient get(FLoggingClient obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

