// automatically generated by the FlatBuffers compiler, do not modify

package mainServer.schemas.FGame;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FTeam extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static FTeam getRootAsFTeam(ByteBuffer _bb) { return getRootAsFTeam(_bb, new FTeam()); }
  public static FTeam getRootAsFTeam(ByteBuffer _bb, FTeam obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FTeam __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public mainServer.schemas.FGame.FClient clients(int j) { return clients(new mainServer.schemas.FGame.FClient(), j); }
  public mainServer.schemas.FGame.FClient clients(mainServer.schemas.FGame.FClient obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int clientsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public mainServer.schemas.FGame.FClient.Vector clientsVector() { return clientsVector(new mainServer.schemas.FGame.FClient.Vector()); }
  public mainServer.schemas.FGame.FClient.Vector clientsVector(mainServer.schemas.FGame.FClient.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createFTeam(FlatBufferBuilder builder,
      int clientsOffset) {
    builder.startTable(1);
    FTeam.addClients(builder, clientsOffset);
    return FTeam.endFTeam(builder);
  }

  public static void startFTeam(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addClients(FlatBufferBuilder builder, int clientsOffset) { builder.addOffset(0, clientsOffset, 0); }
  public static int createClientsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startClientsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endFTeam(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FTeam get(int j) { return get(new FTeam(), j); }
    public FTeam get(FTeam obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

