// automatically generated by the FlatBuffers compiler, do not modify

package mainServer.schemas.FWaitingRoomsList;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FWaitingRoom extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static FWaitingRoom getRootAsFWaitingRoom(ByteBuffer _bb) { return getRootAsFWaitingRoom(_bb, new FWaitingRoom()); }
  public static FWaitingRoom getRootAsFWaitingRoom(ByteBuffer _bb, FWaitingRoom obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FWaitingRoom __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int id() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String city() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer cityAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer cityInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String host() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer hostAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer hostInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public int clientsLogged() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int clientsMax() { int o = __offset(12); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int status() { int o = __offset(14); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createFWaitingRoom(FlatBufferBuilder builder,
      int id,
      int cityOffset,
      int hostOffset,
      int clientsLogged,
      int clientsMax,
      int status) {
    builder.startTable(6);
    FWaitingRoom.addStatus(builder, status);
    FWaitingRoom.addClientsMax(builder, clientsMax);
    FWaitingRoom.addClientsLogged(builder, clientsLogged);
    FWaitingRoom.addHost(builder, hostOffset);
    FWaitingRoom.addCity(builder, cityOffset);
    FWaitingRoom.addId(builder, id);
    return FWaitingRoom.endFWaitingRoom(builder);
  }

  public static void startFWaitingRoom(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addId(FlatBufferBuilder builder, int id) { builder.addInt(0, id, 0); }
  public static void addCity(FlatBufferBuilder builder, int cityOffset) { builder.addOffset(1, cityOffset, 0); }
  public static void addHost(FlatBufferBuilder builder, int hostOffset) { builder.addOffset(2, hostOffset, 0); }
  public static void addClientsLogged(FlatBufferBuilder builder, int clientsLogged) { builder.addInt(3, clientsLogged, 0); }
  public static void addClientsMax(FlatBufferBuilder builder, int clientsMax) { builder.addInt(4, clientsMax, 0); }
  public static void addStatus(FlatBufferBuilder builder, int status) { builder.addInt(5, status, 0); }
  public static int endFWaitingRoom(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FWaitingRoom get(int j) { return get(new FWaitingRoom(), j); }
    public FWaitingRoom get(FWaitingRoom obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

