// automatically generated by the FlatBuffers compiler, do not modify

package mainServer.schemas.FWaitingRoomsList;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FWaitingRoom extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static FWaitingRoom getRootAsFWaitingRoom(ByteBuffer _bb) { return getRootAsFWaitingRoom(_bb, new FWaitingRoom()); }
  public static FWaitingRoom getRootAsFWaitingRoom(ByteBuffer _bb, FWaitingRoom obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FWaitingRoom __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String city() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer cityAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer cityInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String host() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer hostAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer hostInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public int clientsLogged() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int clientsMax() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean status() { int o = __offset(12); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createFWaitingRoom(FlatBufferBuilder builder,
      int cityOffset,
      int hostOffset,
      int clientsLogged,
      int clientsMax,
      boolean status) {
    builder.startTable(5);
    FWaitingRoom.addClientsMax(builder, clientsMax);
    FWaitingRoom.addClientsLogged(builder, clientsLogged);
    FWaitingRoom.addHost(builder, hostOffset);
    FWaitingRoom.addCity(builder, cityOffset);
    FWaitingRoom.addStatus(builder, status);
    return FWaitingRoom.endFWaitingRoom(builder);
  }

  public static void startFWaitingRoom(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addCity(FlatBufferBuilder builder, int cityOffset) { builder.addOffset(0, cityOffset, 0); }
  public static void addHost(FlatBufferBuilder builder, int hostOffset) { builder.addOffset(1, hostOffset, 0); }
  public static void addClientsLogged(FlatBufferBuilder builder, int clientsLogged) { builder.addInt(2, clientsLogged, 0); }
  public static void addClientsMax(FlatBufferBuilder builder, int clientsMax) { builder.addInt(3, clientsMax, 0); }
  public static void addStatus(FlatBufferBuilder builder, boolean status) { builder.addBoolean(4, status, false); }
  public static int endFWaitingRoom(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FWaitingRoom get(int j) { return get(new FWaitingRoom(), j); }
    public FWaitingRoom get(FWaitingRoom obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

