// automatically generated by the FlatBuffers compiler, do not modify

package mainServer.schemas.FWaitingRoom;

public final class FVehicleType {
  private FVehicleType() { }
  public static final byte Pedestrian = 0;
  public static final byte Cyclist = 1;
  public static final byte Car = 2;

  public static final String[] names = { "Pedestrian", "Cyclist", "Car", };

  public static String name(int e) { return names[e]; }
}

