// automatically generated by the FlatBuffers compiler, do not modify

package UPZP.FChooseWaitingRoom;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FChooseWaitingRoom extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static FChooseWaitingRoom getRootAsFChooseWaitingRoom(ByteBuffer _bb) { return getRootAsFChooseWaitingRoom(_bb, new FChooseWaitingRoom()); }
  public static FChooseWaitingRoom getRootAsFChooseWaitingRoom(ByteBuffer _bb, FChooseWaitingRoom obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FChooseWaitingRoom __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int id() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createFChooseWaitingRoom(FlatBufferBuilder builder,
      int id) {
    builder.startTable(1);
    FChooseWaitingRoom.addId(builder, id);
    return FChooseWaitingRoom.endFChooseWaitingRoom(builder);
  }

  public static void startFChooseWaitingRoom(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addId(FlatBufferBuilder builder, int id) { builder.addInt(0, id, 0); }
  public static int endFChooseWaitingRoom(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishFChooseWaitingRoomBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedFChooseWaitingRoomBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FChooseWaitingRoom get(int j) { return get(new FChooseWaitingRoom(), j); }
    public FChooseWaitingRoom get(FChooseWaitingRoom obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

