// automatically generated by the FlatBuffers compiler, do not modify

package mainServer.schemas.FMessage;

public final class FMessageType {
  private FMessageType() { }
  public static final byte StartGame = 0;
  public static final byte LeaveRoom = 1;

  public static final String[] names = { "StartGame", "LeaveRoom", };

  public static String name(int e) { return names[e]; }
}

