// automatically generated by the FlatBuffers compiler, do not modify

package mainServer.schemas.FMessage;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FMessage extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static FMessage getRootAsFMessage(ByteBuffer _bb) { return getRootAsFMessage(_bb, new FMessage()); }
  public static FMessage getRootAsFMessage(ByteBuffer _bb, FMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte messageType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static int createFMessage(FlatBufferBuilder builder,
      byte messageType) {
    builder.startTable(1);
    FMessage.addMessageType(builder, messageType);
    return FMessage.endFMessage(builder);
  }

  public static void startFMessage(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addMessageType(FlatBufferBuilder builder, byte messageType) { builder.addByte(0, messageType, 0); }
  public static int endFMessage(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishFMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedFMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FMessage get(int j) { return get(new FMessage(), j); }
    public FMessage get(FMessage obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

